services:
  minio:
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z-cpuv1
    container_name: baldino
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - baldino:/data
      - ./init:/init
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: >
      sh -c '
        minio server /data --console-address ":9001" &

        until curl -s http://localhost:9000/minio/health/ready > /dev/null; do sleep 1; done;

        mc alias set local http://localhost:9000 "$$MINIO_ROOT_USER" "$$MINIO_ROOT_PASSWORD"

        mc admin policy create local readonly /init/readonly-policy.json || true

        mc admin user add local "$$MINIO_EAR_USER" "$$MINIO_EAR_PASSWORD" || true
        mc admin policy attach local readonly --user "$$MINIO_EAR_USER" || true

        mc ls local/$$MINIO_PUBLIC_BUCKET || mc mb local/$$MINIO_PUBLIC_BUCKET
        mc anonymous set download local/$$MINIO_PUBLIC_BUCKET

        wait
      '

volumes:
  baldino:
